
import {catchAsyncError} from "../middlewares/catchAsyncError.js"
import ErrorHandler from "../middlewares/error.js"


export const employerGetAllApplication = catchAsyncError(async(req, res, next) => {
    
})
